//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSitemap
    {
        public AspNetSitemap()
        {
            this.AspNetSitemapNodes = new HashSet<AspNetSitemapNode>();
        }
    
        public string Id { get; set; }
        public string ApplicationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public bool Inactive { get; set; }
    
        public virtual AspNetApplication AspNetApplication { get; set; }
        public virtual ICollection<AspNetSitemapNode> AspNetSitemapNodes { get; set; }
    }
}
