//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSitemapNode
    {
        public AspNetSitemapNode()
        {
            this.AspNetSitemapNodes1 = new HashSet<AspNetSitemapNode>();
        }
    
        public string Id { get; set; }
        public string SitemapId { get; set; }
        public string PermissionId { get; set; }
        public string ParentNodeId { get; set; }
        public string Href { get; set; }
        public string Class { get; set; }
        public string Title { get; set; }
        public string Target { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public bool Inactive { get; set; }
    
        public virtual AspNetPermission AspNetPermission { get; set; }
        public virtual ICollection<AspNetSitemapNode> AspNetSitemapNodes1 { get; set; }
        public virtual AspNetSitemapNode AspNetSitemapNode1 { get; set; }
        public virtual AspNetSitemap AspNetSitemap { get; set; }
    }
}
