//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetApplicationUserRole
    {
        public string ApplicationId { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public bool Inactive { get; set; }
    
        public virtual AspNetApplication AspNetApplication { get; set; }
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
