//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public System.Guid sz_region_id { get; set; }
        public System.Guid sz_region_type_id { get; set; }
        public string sz_fips_code { get; set; }
        public string sz_abbreviation { get; set; }
        public string sz_name { get; set; }
        public string sz_description { get; set; }
        public string sz_mdr_code { get; set; }
        public string sz_gnis_code { get; set; }
        public Nullable<decimal> n_longitude { get; set; }
        public Nullable<decimal> n_latitude { get; set; }
        public string sz_image_location { get; set; }
        public string sz_modified_by { get; set; }
        public System.DateTime dt_modified { get; set; }
        public bool b_inactive { get; set; }
        public byte[] sz_timestamp { get; set; }
    }
}
