//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SAMPLE_TB
    {
        public int N_SAMPLE_SYSID { get; set; }
        public int N_SERVICE_X_ACTIVITY_TYPE_SYSID { get; set; }
        public int N_SAMPLE_TYPE_SYSID { get; set; }
        public int N_QUANTITY { get; set; }
        public Nullable<int> N_TEMPORARY_ID { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual REF_SAMPLE_TYPE_TB REF_SAMPLE_TYPE_TB { get; set; }
        public virtual TRN_SERVICE_X_ACTIVITY_TYPE_TB TRN_SERVICE_X_ACTIVITY_TYPE_TB { get; set; }
    }
}
