//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SERVICE_X_ACTIVITY_TYPE_TB
    {
        public TRN_SERVICE_X_ACTIVITY_TYPE_TB()
        {
            this.TRN_SAMPLE_TB = new HashSet<TRN_SAMPLE_TB>();
        }
    
        public int N_SERVICE_X_ACTIVITY_TYPE_SYSID { get; set; }
        public int N_SERVICE_SYSID { get; set; }
        public int N_ACTIVITY_TYPE_SYSID { get; set; }
        public int N_PROGRAM_SYSID { get; set; }
        public Nullable<int> N_SUBPROGRAM_SYSID { get; set; }
        public Nullable<int> N_OPTION_SYSID { get; set; }
        public string SZ_CODE { get; set; }
        public decimal N_TIME { get; set; }
        public string SZ_FIPS_CODE { get; set; }
        public string SZ_ADDRESS { get; set; }
        public string SZ_IDENTICAL_SERVICE_CODE { get; set; }
        public Nullable<int> N_TEMPORARY_ID { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual REF_ACTIVITY_TYPE_TB REF_ACTIVITY_TYPE_TB { get; set; }
        public virtual REF_OPTION_TB REF_OPTION_TB { get; set; }
        public virtual REF_PROGRAM_TB REF_PROGRAM_TB { get; set; }
        public virtual REF_SUBPROGRAM_TB REF_SUBPROGRAM_TB { get; set; }
        public virtual ICollection<TRN_SAMPLE_TB> TRN_SAMPLE_TB { get; set; }
        public virtual TRN_SERVICE_TB TRN_SERVICE_TB { get; set; }
    }
}
