//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EH.TimeTrackNet.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SERVICE_TB
    {
        public TRN_SERVICE_TB()
        {
            this.TRN_SERVICE_X_ACTIVITY_TYPE_TB = new HashSet<TRN_SERVICE_X_ACTIVITY_TYPE_TB>();
        }
    
        public int N_SERVICE_SYSID { get; set; }
        public System.DateTime DT_SERVICE { get; set; }
        public string SZ_USER_NAME { get; set; }
        public int N_WORKER_NUMBER { get; set; }
        public Nullable<int> N_MILEAGE_QUANTITY { get; set; }
        public Nullable<decimal> N_MILEAGE_TIME { get; set; }
        public Nullable<int> N_CALLS_QUANTITY { get; set; }
        public Nullable<decimal> N_CALLS_TIME { get; set; }
        public Nullable<int> N_CONSULT_QUANTITY { get; set; }
        public Nullable<decimal> N_CONSULT_TIME { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual ICollection<TRN_SERVICE_X_ACTIVITY_TYPE_TB> TRN_SERVICE_X_ACTIVITY_TYPE_TB { get; set; }
    }
}
